version: "3.9"
services:
  # frontend:
  #   build:
  #     context: ./frontend
  #   ports:
  #     - "5173:5173"
  #   command: npm run dev
  #   environment:
  #     - NODE_ENV=development
  #     - VITE_API_URL=http://backend:3000
  #   depends_on:
  #     - backend

  # backend:
  #   build:
  #     context: ./backend
  #     args:
  #       NODE_ENV: development
  #   ports:
  #     - "3000:3000"
  #   command: npm run dev
  #   environment:
  #     - NODE_ENV=development
  #     - DB_HOST=db
  #     - DB_PORT=5432
  #     - DB_USER=admin
  #     - DB_PASSWORD=admin
  #     - DB_NAME=appdb
  #   depends_on:
  #     - db

  # db:
  #   image: postgres:15
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: pepita
  #     POSTGRES_DB: postgres
  #   volumes:
  #     - ./setup_database.sql:/docker-entrypoint-initdb.d/setup.sql

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    # depends_on:
    #   - db    
